image: public.ecr.aws/docker/library/python:slim-bullseye
inline_script:
- |+
  cat > /tmp/engine.json <<EOF
  {
    "model": "/fsx/pretrained-models/meta-llama/Meta-Llama-3-8B-Instruct",
    "disable_log_requests": true,
    "tensor_parallel_size": 8,
    "max_num_seqs": 8,
    "dtype": "float16"
  }

  EOF
pre_script:
  - mkdir -p $CONFIG_ROOT
  - cp /tmp/engine.json $CONFIG_ROOT/engine.json
process:
  env:
    - name: CONFIG_ROOT
      value: /efs/home/{{ .Release.Name }}/config
