image: public.ecr.aws/docker/library/python:slim-bullseye
resources:
  requests:
    cpu: "1000m"
    memory: "512Mi"
  limits:
    cpu: "2000m"
    memory: "8192Mi"
pvc:
  - name: pv-fsx
    mount_path: /fsx
  - name: pv-efs
    mount_path: /efs
env: []
engine_path: /fsx/rayserve/engines/vllm_neuronx_asyncllmengine.zip
