image: public.ecr.aws/docker/library/python:slim-bullseye
inline_script:
- |+
  cat > /tmp/engine.json <<EOF
  {
    "pretrained_model_name_or_path": "/fsx/pretrained-models/meta-llama/Meta-Llama-3-8B-Instruct",
    "n_positions": 8192,
    "tp_degree": 8,
    "batch_size": 1,
    "amp": "f16",
    "neuron_config": {
      "on_device_embedding": {
        "max_length": 8192, 
        "top_k": 50, 
        "do_sample": true
      }
    }
  }

  EOF
pre_script:
  - mkdir -p $CONFIG_ROOT
  - cp /tmp/engine.json $CONFIG_ROOT/engine.json
process:
  env:
    - name: CONFIG_ROOT
      value: /efs/home/{{ .Release.Name }}/config
