---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redpajama-data-{{ .Release.Name }}
data:
  redpajama-data.sh: |
    #!/bin/bash

    yum install -y wget

    if [ -f $DATA_DIR/data.jsonl ]
    then 
      echo "$DATA_DIR/data.jsonl exists" 
      exit 0
    fi
    mkdir -p $DATA_DIR
    echo "Data dir: $DATA_DIR"
    
    wget -O $DATA_DIR/data.jsonl https://data.together.xyz/redpajama-data-1T/v1.0.0/wikipedia/wiki.jsonl
---
apiVersion: v1
kind: Pod
metadata:
  name: redpajama-data-{{ .Release.Name }}
  annotations:
    karpenter.sh/do-not-disrupt: "true"
    sidecar.istio.io/inject: 'false'
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  restartPolicy: Never
  volumes:
  - name: pv
    persistentVolumeClaim:
      claimName: {{ .Values.pvc.name }} 
  - name: config
    configMap:
      defaultMode: 420
      items:
      - key: redpajama-data.sh
        mode: 365
        path: redpajama-data.sh
      name: redpajama-data-{{ .Release.Name }}
  containers:
  - name: redpajama-data
    env:
    - name: DATA_DIR 
      value: {{ .Values.pvc.mount_path }}/{{ .Values.pvc.data_path }}
    command:
    -  sh 
    - /etc/config/redpajama-data.sh
    image: amazonlinux
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /etc/config
      name: config
    - mountPath: {{ .Values.pvc.mount_path }}
      name: pv
    resources:
      requests:
        cpu: "256m"
        memory: "64Mi"
      limits:
        cpu: "1000m"
        memory: "256Mi"
