apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lws-webhook-server-cert
  namespace: lws-system
  labels:
    app.kubernetes.io/name: certificate
    app.kubernetes.io/instance: lws-webhook-server-cert
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: lws
    app.kubernetes.io/part-of: lws
    app.kubernetes.io/managed-by: Helm
spec:
  commonName: lws-webhook-service.{{ .Release.Namespace }}.svc
  dnsNames:
  - lws-webhook-service.{{ .Release.Namespace }}.svc
  - lws-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  isCA: true
  issuerRef:
    kind: Issuer
    name: lws-selfsigned-issuer
  secretName: lws-webhook-server-cert
