apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: lws-selfsigned-issuer
  namespace: lws-system
  labels:
    app.kubernetes.io/name: certificate
    app.kubernetes.io/instance: lws-webhook-server-cert
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: lws
    app.kubernetes.io/part-of: lws
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
