---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: lws
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: lws
    app.kubernetes.io/managed-by: Helm
  name: lws-webhook-service
  namespace: lws-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
---