apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: lws
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: lws
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: lws-controller-manager
  namespace: lws-system