apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: lws-validating-webhook-configuration
  namespace: lws-system
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/lws-webhook-server-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: lws-webhook-service
      namespace: lws-system
      path: /validate-leaderworkerset-x-k8s-io-v1-leaderworkerset
  failurePolicy: Fail
  name: vleaderworkerset.kb.io
  rules:
  - apiGroups:
    - leaderworkerset.x-k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - leaderworkersets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: lws-webhook-service
      namespace: lws-system
      path: /validate--v1-pod
  failurePolicy: Fail
  name: vpod.kb.io
  objectSelector:
    matchExpressions:
    - key: leaderworkerset.sigs.k8s.io/name
      operator: Exists
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None